#ifndef JAVA_LANG_CLASSNOTFOUNDEXCEPTION_H
#define JAVA_LANG_CLASSNOTFOUNDEXCEPTION_H

#include "java_lang_Exception.h"

typedef struct java_lang_ClassNotFoundException {
	java_lang_Exception instance_header;
} java_lang_ClassNotFoundException;

typedef struct java_lang_ClassNotFoundException_class {
	java_lang_Object_class class_header;
} java_lang_ClassNotFoundException_class;

java_lang_ClassNotFoundException_class java_lang_ClassNotFoundException_class_instance;

#endif